### ISSUE TITLE
【vue】父组件修改子组件样式

### ISSUE THREAD

**Issue by Easay** [Easay/issuesSets#120]
封装好的组件设定的样式不一定适用所有场景，当我们在实际页面引入组件后，有时候还需要进行样式修改。为了防止全局污染，通常组件封装时会为style标签设置scoped属性。如果要在父组件中修改子组件的样式，有两种方式：

方式一：
```css
.protocol-wrapper {
  /deep/ .protocol-text {
    display: flex;
    align-items: flex-start;
    position: relative;
  }
}
```
方式二：
```css
.protocol-wrapper {
  >>> .protocol-text {
    display: flex;
    align-items: flex-start;
    position: relative;
  }
}
```
其中，protocol-wrapper和 protocol-text都是子组件中的类名。
上述样式的修改仅作用于本页面，不会影响使用该子组件的其他页面。保证了样式覆盖，又没有造成全局污染。
