### ISSUE TITLE
【CSS】transition和animation

### ISSUE THREAD

**Issue by Easay** [Easay/issuesSets#139]
### transition

`transition`属性是 `transition-property`，`transition-duration`，`transition-timing-function` 和 `transition-delay`的一个简写属性。

过渡可以为一个元素在不同状态之间切换的时候定义不同的过渡效果。比如在不同的伪元素之间切换。transition属性可以被指定为一个或多个 CSS 属性的过渡效果，多个属性之间用逗号进行分隔。

```css
.box{
    width: 200px;
    height: 80px;
    background-color: aquamarine;
    transition: width 2s;
}
.box:hover{
    width: 100px;
    height: 80px;
    background-color: cadetblue;
}
```
`transition`写在box类中，当hover触发时过渡属性生效，当hover不触发时，过渡属性仍会生效；如果写在hover伪类中，鼠标移开将没有过渡效果。

#### timing-funtion

规定过渡时的加速曲线，默认是ease（线性）。
