### ISSUE TITLE
【CSS】不常用的css属性

### ISSUE THREAD

**Issue by Easay** [Easay/issuesSets#140]
### box-shadow

`box-shadow`用来设置盒子的阴影。
```css
box-shadow: x轴偏移 y轴偏移 模糊半径 扩展半径 颜色
```
模糊半径值越大，显得越模糊。
![image](https://user-images.githubusercontent.com/52184434/130449069-15acab8a-ac35-4964-95d4-7dac10b82945.png)
```css
.box{
    width: 100px;
    height: 100px;
    box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.3);
    background-color: chocolate;
}
```
`box-shadow`可以使用`inset`关键字设置内阴影，营造一种元素被镂空的效果。
![image](https://user-images.githubusercontent.com/52184434/130449549-4f755d26-b7fe-4df3-94d4-421f621daef0.png)
```css
box-shadow: inset 10px 10px 10px rgba(0, 0, 0, 0.3)
```
