### ISSUE TITLE
[css]题1. 用css创建一个三角形

### ISSUE THREAD

**Issue by Easay** [Easay/issuesSets#7]
```css
```

**Comment by Easay** [comment]
### clip-path
使用裁剪的方式创建元素的可视区域。[clip-path](https://developer.mozilla.org/zh-CN/docs/Web/CSS/clip-path)
```css
/*画一个三角形*/
clip-path: polygon(0 100%,50% 0, 100% 100%); 
/*画一个圆*/
clip-path: circle(40%);
```

**Comment by Easay** [comment]
https://blog.csdn.net/LZGS_4/article/details/46827761
### 画圆
```css
.circle {
    border-radius: 50%
}
```
### 画半圆
```css
.container{
    width: 100px;
    height: 50px;
    background: red;
    border-radius: 50px 50px 0 0;
}
```
### 画扇形
```css
.container{
    width: 50px;
    height: 50px;
    background: red;
    border-radius: 50px 0 0;
}
```
![image](https://user-images.githubusercontent.com/52184434/129560686-68243bbd-bded-4d5b-934b-d6ad935f689c.png)

**Comment by Easay** [comment]
### 画气泡
```css
.buble-container {
    margin-top: 20px;
    width: 100px;
}
.buble{
    position: relative;
    width: 100px;
    height: 40px;
    border-radius: 10px;
    background: tomato;
}
.buble::after{
    content: ' ';
    position: absolute;
    width: 0;
    height: 0;
    border-width: 8px 8px 0;
    border-style: solid;
    border-color: tomato transparent transparent;
    top: 40px;
    left: 10px;
}
```
```html
<div class="buble-container">
    <div class="buble">
    </div>
</div>
```
