### ISSUE TITLE
【性能优化】雪碧图（CSS Sprites）

### ISSUE THREAD

**Issue by Easay** [Easay/issuesSets#89]
不使用雪碧图，单纯调用小图片有以下缺点：
- 请求文件过多，引发性能问题。
- 每个图标的显示都产生一个HTTP请求

如果网站开发中遇到小图标显示，优先考虑雪碧图实现。

### 将图标合成为雪碧图：webpack
**实现步骤：**
1.配置webpack开发环境；
2.安装雪碧图依赖模块：`webpack-spritesmith`；
3.将素材小图标放入对应文件夹，编写配置文件-`webpack.config.js`
```js
var path = require('path');
var SpritesmithPlugin = require('webpack-spritesmith');

module.exports = {
    entry: path.resolve(__dirname, 'app/main.js'),
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js',
    },
    plugins: [
        new SpritesmithPlugin({
          src: {
            cwd: path.resolve(__dirname, 'app/images/'),
            glob: '*.png'
          },
          target: {
            image: path.resolve(__dirname, 'build/images/sprite.png'),
            css: path.resolve(__dirname, 'build/css/sprite.css')
          },
          apiOptions: {
            cssImageRef: '../images/sprite.png'
          },
          spritesmithOptions: {
            algorithm: 'top-down'
          }
        })
    ]
};
```
4.在配置文件同级目录下，执行命令：
```js
webpack
```
### 操作雪碧图，截取图标
```css
.ps_demo_wrap .weibo_icon,
.ps_demo_wrap .qq_icon,
.ps_demo_wrap .douban_icon,
.ps_demo_wrap .renren_icon{
  width:54px;
  height:54px;
  background:url("../images/CssGaga.png");
}
.ps_demo_wrap .weibo_icon{ background-position: -168px 0px; }
.ps_demo_wrap .qq_icon{ background-position: -56px 0px; }
.ps_demo_wrap .douban_icon{ background-position: 0px 0px; }
.ps_demo_wrap .renren_icon{ background-position: -112px 0px; }
```
